### ISSUE TITLE
Typo in getting started?

### ISSUE THREAD

**Issue by Aariq** [NIEHS/chopin#103]
https://github.com/NIEHS/chopin/blob/e8165943778eb10e3035d1a71f1faaacc57f07b2/vignettes/v01_start.Rmd#L179-L184

I think maybe the code block is in the wrong place here?  I suspect it should read:

>Users should disable s2 spherical geometry mode in sf by setting `sf::sf_use_s2(FALSE)`. Running any `chopin` functions at spherical or three-dimensional (e.g., including M/Z dimensions) geometries may produce incorrect or unexpected results.

**Comment by sigmafelix** [comment]
Thank you for reporting the issue @Aariq. I agree that the code block in the main text is more visible than separating it out into a code block. (https://github.com/NIEHS/chopin/commit/dc7dc3be1fa218c9b66841598cf4f71f5cd0109c)
