### ISSUE TITLE
Develop the pkgdown static site

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/chopin#53]

**Comment by sigmafelix** [comment]
@Spatiotemporal-Exposures-and-Toxicology Thank you for bringing it up. For a custom theme, we will need to have a fixed palette with hex codes for major colors. I will change the theme into minty in _pkgdown.yml.

**Comment by sigmafelix** [comment]
Minty was applied to the current version of pkgdown. One more thing to do is to host test reports in GitHub page (cf. NIEHS/amadeus#73)
